#version 450

#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_shader_8bit_storage : require

#include "common.h"

layout(local_size_x = TILE_SIZE, local_size_y = TILE_SIZE, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D Textures[];
layout(set = 0, binding = 1) uniform sampler2D Depth;
layout(set = 0, binding = 2) writeonly buffer LightIndices {
    int lightIndices[];
};
layout(set = 0, binding = 4) readonly buffer TileFrustums {
    Frustum tileFrustums[];
};

layout(buffer_reference, std430) readonly buffer MeshletBuffer{ 
	Meshlet meshlets[];
};
layout(buffer_reference, std430) readonly buffer MeshletVertexBuffer{ 
	uint meshletVertices[];
};
layout(buffer_reference, std430) readonly buffer MeshletTriangleBuffer{ 
	uint8_t meshletTriangles[];
};
layout(buffer_reference, std430) readonly buffer MeshletBoundBuffer{ 
	MeshletBounds meshletBounds[];
};

layout(buffer_reference, std430) readonly buffer VertexBuffer{ 
	Vertex vertices[];
};
layout(buffer_reference, std430) readonly buffer MaterialBuffer{
	Material materials[];
};
layout(buffer_reference, std430) readonly buffer LightBuffer{
	Light lights[];
};
layout(buffer_reference, std430) readonly buffer MeshViewBuffer{
	MeshView meshViews[];
};
layout(set = 0, binding = 3) uniform BufferAddresses {
	MeshletBuffer meshletBuffer;
	MeshletVertexBuffer meshletVertices;
	MeshletTriangleBuffer meshletTriangles;
	MeshletBoundBuffer meshletBounds;

	MeshViewBuffer meshViewBuffer;
	VertexBuffer vertexBuffer;
	MaterialBuffer materialBuffer;
	LightBuffer lightBuffer;
};

layout(push_constant, std430) uniform constant
{
	mat4 projView;
	mat4 view;
	mat4 proj;
	vec4 camPos;
	SceneInfo sceneInfo;
};

bool SphereInsidePlane(Sphere sphere, Plane plane) {
    return dot(plane.normal, sphere.pos) - plane.dist < -sphere.r;
}
bool SphereInsideFrustum( Sphere sphere, Frustum frustum, float zNear, float zFar ) {
    if (sphere.pos.z - sphere.r > zNear || sphere.pos.z + sphere.r < zFar)
        return false;

    for(uint i = 0; i < 4; i++) {
        if( SphereInsidePlane(sphere, frustum.planes[i]) )
          return false;
    }

    return true;
}

bool PointInsidePlane(vec3 p, Plane plane) {
    return dot(plane.normal, p) - plane.dist < 0;
}
bool ConeInsidePlane(Cone cone, Plane plane) {
    vec3 m = cross( cross(plane.normal, cone.dir), cone.dir);
    vec3 q = cone.tip + cone.dir * cone.height - m * cone.r;
    return PointInsidePlane(cone.tip, plane) && PointInsidePlane(q, plane);
}
bool ConeInsideFrustum(Cone cone, Frustum frustum, float zNear, float zFar) {
    Plane near;
    near.normal = vec3(0, 0, -1);
    near.dist   = -zNear;
    Plane far;
    far.normal = vec3(0, 0, 1);
    far.dist   = zFar;

    if(ConeInsidePlane(cone, near) || ConeInsidePlane(cone, far))
        return false;

    for(uint i = 0; i < 4; i++) {
        if(ConeInsidePlane(cone, frustum.planes[i]))
            return false;
    }
}

vec4 ClipToView(vec4 clip) {
    vec4 view = inverse(proj) * clip;
    view = view / view.w;
    return view;
}

shared uint minDepthInt;
shared uint maxDepthInt;
shared uint visiblePointLightsCount;
shared uint visibleSpotLightsCount;
shared Frustum frustum;

void main() {
	ivec2 tileID     = ivec2(gl_WorkGroupID.xy);
	ivec2 tileNumber = ivec2(gl_NumWorkGroups.xy);
	uint index = tileID.y * tileNumber.x + tileID.x;

    if (gl_LocalInvocationIndex == 0) {
	    minDepthInt = 0xffffffff;
	    maxDepthInt = 0;
		visiblePointLightsCount = 0;
        visibleSpotLightsCount  = 0;
        frustum = tileFrustums[index];
    }

    barrier();

    // Compute min and max depth of tile.
    vec2 uv = gl_GlobalInvocationID.xy / vec2(sceneInfo.width, sceneInfo.height);
    float depth    = texture(Depth, uv).x;
    uint  depthInt = floatBitsToUint(depth);
    
    atomicMax(maxDepthInt, depthInt);
    atomicMin(minDepthInt, depthInt);

    barrier();

    // Compute tile frustum.
    float minDepth = uintBitsToFloat(minDepthInt);
	float maxDepth = uintBitsToFloat(maxDepthInt);
    float minDepthView = ClipToView(vec4(0, 0, minDepth, 1)).z;
    float maxDepthView = ClipToView(vec4(0, 0, maxDepth, 1)).z;
    float nearClipView = ClipToView(vec4(0, 0, 0, 1)).z;

    Plane minPlane;
    minPlane.normal = vec3(0, 0, -1);
    minPlane.dist   = -minDepthView;

    // Cull point lights.
	uint offset = index * MAX_VISIBLE_LIGHTS;

    if (gl_LocalInvocationIndex < sceneInfo.pointLightCount) {
        Light light = lightBuffer.lights[gl_LocalInvocationIndex];
    
        Sphere s;
        s.pos = (view * vec4(light.pos, 1)).xyz;
        s.r   = light.radius;
    
        if (SphereInsideFrustum(s, frustum, minDepthView, maxDepthView)) {
			uint currentCount = atomicAdd(visiblePointLightsCount, 1);
			lightIndices[offset + currentCount] = int(gl_LocalInvocationIndex);
		}
    }

    barrier();

    // Cull spot lights.
	mat4 normalTransform = transpose(inverse(view));
    if (gl_LocalInvocationIndex < sceneInfo.spotLightCount) {
        Light light = lightBuffer.lights[gl_LocalInvocationIndex + sceneInfo.pointLightCount];

        //Cone c;
        //c.tip = (view * vec4(light.pos, 1)).xyz;
        //c.dir = (normalTransform * light.lightDir).xyz;
        //c.height = light.radius;
        //c.r   = tan(radians(light.cutoff)) * light.radius;
        //
        //if (ConeInsideFrustum(c, frustum, minDepthView, maxDepthView)) {
		//	uint currentCount = atomicAdd(visibleSpotLightsCount, 1);
		//	lightIndices[offset + visiblePointLightsCount + 1 + currentCount] = int(gl_LocalInvocationIndex + sceneInfo.pointLightCount);
		//}
        Sphere s;
        s.pos = (view * vec4(light.pos, 1)).xyz;
        s.r   = light.radius;
    
        if (SphereInsideFrustum(s, frustum, minDepthView, maxDepthView)) {
			uint currentCount = atomicAdd(visibleSpotLightsCount, 1);
			lightIndices[offset + visiblePointLightsCount + 1 + currentCount] = int(gl_LocalInvocationIndex + sceneInfo.pointLightCount);
        }
    }

    barrier();

    if(gl_LocalInvocationIndex == 0) {
        if (visiblePointLightsCount < MAX_VISIBLE_LIGHTS)
            lightIndices[offset + visiblePointLightsCount] = -1;

        if (visibleSpotLightsCount < MAX_VISIBLE_LIGHTS)
            lightIndices[offset + visiblePointLightsCount + 1 + visibleSpotLightsCount] = -1;
    }
}