#version 450

#extension GL_GOOGLE_include_directive : enable
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_shader_8bit_storage : require

#include "common.h"

layout(local_size_x = TILE_SIZE, local_size_y = TILE_SIZE, local_size_z = 1) in;

layout(set = 0, binding = 0) uniform sampler2D Textures[];
layout(set = 0, binding = 1) uniform sampler2D Depth;
layout(set = 0, binding = 2) writeonly buffer LightIndices {
    int lightIndices[];
};

layout(buffer_reference, std430) readonly buffer MeshletBuffer{ 
	Meshlet meshlets[];
};
layout(buffer_reference, std430) readonly buffer MeshletVertexBuffer{ 
	uint meshletVertices[];
};
layout(buffer_reference, std430) readonly buffer MeshletTriangleBuffer{ 
	uint8_t meshletTriangles[];
};
layout(buffer_reference, std430) readonly buffer MeshletBoundBuffer{ 
	MeshletBounds meshletBounds[];
};

layout(buffer_reference, std430) readonly buffer VertexBuffer{ 
	Vertex vertices[];
};
layout(buffer_reference, std430) readonly buffer MaterialBuffer{
	Material materials[];
};
layout(buffer_reference, std430) readonly buffer LightBuffer{
	Light lights[];
};
layout(buffer_reference, std430) readonly buffer MeshViewBuffer{
	MeshView meshViews[];
};
layout(push_constant, std430) uniform constant
{
	mat4 projView;
	mat4 worldTransform;
	vec4 camPos;
	SceneInfo sceneInfo;

	MeshletBuffer meshletBuffer;
	MeshletVertexBuffer meshletVertices;
	MeshletTriangleBuffer meshletTriangles;
	MeshletBoundBuffer meshletBounds;

	MeshViewBuffer meshViewBuffer;
	VertexBuffer vertexBuffer;
	MaterialBuffer materialBuffer;

	LightBuffer lightBuffer;
};

vec4 ClipToView(vec4 clip) {
    vec4 view = inverse(projView) * clip;
    view = view / view.w;
    return view;
}

vec4 ScreenToView(vec4 screen) {
    vec2 texCoord = screen.xy / vec2(sceneInfo.width, sceneInfo.height);
    vec4 clip = vec4(vec2( texCoord.x, 1.0f - texCoord.y) * 2.0f - 1.0f, screen.z, screen.w );
    return ClipToView(clip);
}

Plane ComputePlane(vec3 p0, vec3 p1, vec3 p2) {
    Plane plane;
    vec3 v0 = p1 - p0;
    vec3 v2 = p2 - p0;
    
    plane.normal   = normalize(cross(v0, v2));
    plane.distance = dot(plane.normal, p0);
    return plane;
}

Frustum GetLightFrustum(vec3 tilePositions[4], vec3 eyePos) {
    Frustum lf;
    lf.left   = ComputePlane(eyePos, tilePositions[2], tilePositions[0]);
    lf.right  = ComputePlane(eyePos, tilePositions[1], tilePositions[3]);
    lf.top    = ComputePlane(eyePos, tilePositions[0], tilePositions[1]);
    lf.bottom = ComputePlane(eyePos, tilePositions[3], tilePositions[2]);
    return lf;
}

bool SphereInsideFrustum( Sphere sphere, Frustum frustum, float zNear, float zFar ) {
    bool result = true;
    if (sphere.pos.z - sphere.r > zNear || sphere.pos.z + sphere.r < zFar)
        result = false;

    if(dot(frustum.top.normal, sphere.pos) - frustum.top.distance < -sphere.r)
        result = false;
    if(dot(frustum.bottom.normal, sphere.pos) - frustum.bottom.distance < -sphere.r)
        result = false;
    if(dot(frustum.left.normal, sphere.pos) - frustum.left.distance < -sphere.r)
        result = false;
    if(dot(frustum.right.normal, sphere.pos) - frustum.right.distance < -sphere.r)
        result = false;

    return result;
}

shared uint minDepth;
shared uint maxDepth;
shared uint visiblePointLightsCount;
shared int visiblePointLights[MAX_VISIBLE_LIGHTS];
shared Frustum frustum;

void main() {
    // Compute tile frustum.
    const vec3 eyePos      = vec3( 0, 0, 0 );
    const uint threadCount = TILE_SIZE * TILE_SIZE;

    if (gl_LocalInvocationIndex == 0) {
		minDepth = 0xFFFFFFFF;
		maxDepth = 0;
		visiblePointLightsCount = 0;

        vec4 screenSpace[4];
        screenSpace[0] = vec4(gl_GlobalInvocationID.xy * TILE_SIZE, -1.0f, 1.0f);
        screenSpace[1] = vec4(vec2(gl_GlobalInvocationID.x + 1, gl_GlobalInvocationID.y) * TILE_SIZE, -1.0f, 1.0f);
        screenSpace[2] = vec4(vec2(gl_GlobalInvocationID.x, gl_GlobalInvocationID.y + 1) * TILE_SIZE, -1.0f, 1.0f);
        screenSpace[3] = vec4(vec2(gl_GlobalInvocationID.x + 1, gl_GlobalInvocationID.y + 1) * TILE_SIZE, -1.0f, 1.0f);

        vec3 viewSpace[4];
        viewSpace[0] = ScreenToView(screenSpace[0]).xyz;
        viewSpace[1] = ScreenToView(screenSpace[1]).xyz;
        viewSpace[2] = ScreenToView(screenSpace[2]).xyz;
        viewSpace[3] = ScreenToView(screenSpace[3]).xyz;

        frustum = GetLightFrustum(viewSpace, eyePos);
	}
    
    barrier();

    // Compute min and max depth of tile.
    vec2 uv = gl_GlobalInvocationID.xy / vec2(sceneInfo.width, sceneInfo.height);
    float depth    = texture(Depth, uv).x;
    uint  depthInt = floatBitsToUint(depth);
    
    atomicMax(maxDepth, depthInt);
    atomicMin(minDepth, depthInt);

    barrier();
    
    // Cull point lights.
    uint passCount = (sceneInfo.pointLightCount + threadCount - 1) / threadCount;

    for (int i = 0; i < passCount; i++) {
        uint lightIndex = i * threadCount + gl_LocalInvocationIndex;
		if (lightIndex >= sceneInfo.pointLightCount)
			break;

		Light light = lightBuffer.lights[lightIndex];
        if (light.lightType == 0) {
            Sphere s;
            s.pos = (projView * vec4(light.pos, 1)).xyz;
            s.r   = light.radius;

            if (SphereInsideFrustum(s, frustum, minDepth, maxDepth)) {
                uint offset = atomicAdd(visiblePointLightsCount, 1);
                if (offset > MAX_VISIBLE_LIGHTS - 1)
                    break;
                visiblePointLights[offset] = i;
            }
        }
	}

    barrier();

    // Write visible lights' indices to list.
    if (gl_LocalInvocationIndex == 0) {
    	ivec2 tileID = ivec2(gl_WorkGroupID.xy);
	    ivec2 tileNumber = ivec2(gl_NumWorkGroups.xy);
	    uint index = tileID.y * tileNumber.x + tileID.x;
        uint offset = index * 1024;

        for (uint i = 0; i < visiblePointLightsCount; i++)
			lightIndices[offset + i] = visiblePointLights[i];

        if (visiblePointLightsCount != 1024)
			lightIndices[offset + visiblePointLightsCount] = -1;
    }
}